README.md: Add a note for init and header name
Just a little note to help anyone that uses it, since the project does not have a documentation, yet the mention to the init command helps compare mdbook config to mdzk, with special attention that without the head `[mdzk]` we get a:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unable to represent the item as a JSON Value

Caused by:
    unsupported None value', src/config.rs:63:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```